### ISSUE TITLE
[Feature] 드롭다운 컴포넌트

### ISSUE THREAD

**Issue by edegiil** [woowa-techcamp-2021/cashbook-1#32]
## 필수 요구사항
1. - [ ] 배열로 `text`, `action`, `buttonAction`(가명) 을 받아와서 렌더링
2. - [ ] `buttonAction`(가명)이 있을 경우 오른쪽에 X 버튼을 렌더링

## 선택 요구사항
1. - [ ] height 애니메이션

## 개발방법
* props에 배열을 넘겨주기

## 다른 접근 방법
* 컴포넌트 자체를 넘겨주기

**Comment by hayoung123** [comment]
다른 방식으로 구현했습니다.
